[profile.default]
src = "src"
test = "test"
script = "ops"
out = "artifacts"
libs = ["lib"]
remappings = []
auto_detect_remappings = true
libraries = []
cache = true
cache_path = ".foundry/cache"
snapshots = "snapshots"
broadcast = ".foundry/broadcast"
allow_paths = [
    "interfaces",
    "contracts",
    "src",
]
include_paths = []
skip = []
force = false
evm_version = "shanghai"
gas_reports = ["*"]
gas_reports_ignore = []
gas_reports_include_tests = false
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 4000
verbosity = 0
ignored_error_codes = [
    "license",
    "func-mutability",
    "pragma-solidity",
    3716,
]
ignored_warnings_from = []
deny_warnings = false
test_failures_file = "cache/test-failures"
show_progress = false
eof = false
transaction_timeout = 120
ffi = false
always_use_create_2_factory = false
prompt_timeout = 120
sender = "0xaffeaffeaffeaffeaffeaffeaffeaffeaffeaffe"
tx_origin = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0"
initial_balance = "0xffffffffffffffffffffffff"
block_number = 1
gas_limit = 9223372036854775807
block_base_fee_per_gas = 7
block_coinbase = "0x0000000000000000000000000000000000000000"
block_timestamp = 1
block_difficulty = 0
block_prevrandao = "0x0000000000000000000000000000000000000000000000000000000000000000"
memory_limit = 33554432
extra_output = [
    "irOptimized",
    "evm.assembly",
]
extra_output_files = ["metadata"]
names = false
sizes = false
via_ir = false
ast = false
no_storage_caching = false
no_rpc_rate_limit = false
use_literal_content = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
build_info = true
compilation_restrictions = []
additional_compiler_profiles = []
assertions_revert = true
isolate = false
disable_block_gas_limit = false
alphanet = false
unchecked_cheatcode_artifacts = false
create2_library_salt = "0x0000000000000000000000000000000000000000000000000000000000000000"
legacy_assertions = false

[[profile.default.fs_permissions]]
access = "read"
path = "out"

[profile.default.optimizer_details]
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = false
optimizerSteps = "u"

[profile.default.rpc_storage_caching]
chains = "all"
endpoints = "all"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "preserve"
hex_underscore = "remove"
single_line_statement_blocks = "preserve"
override_spacing = false
wrap_comments = false
ignore = []
contract_new_lines = false
sort_imports = false

[doc]
out = "docs"
title = ""
book = "book.toml"
homepage = "README.md"
ignore = []

[fuzz]
runs = 10000
max_test_rejects = 120000
dictionary_weight = 40
include_storage = true
include_push_bytes = true
max_fuzz_dictionary_addresses = 15728640
max_fuzz_dictionary_values = 6553600
gas_report_samples = 256
failure_persist_dir = "cache/fuzz"
failure_persist_file = "failures"
show_logs = false

[invariant]
runs = 256
depth = 100
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
max_fuzz_dictionary_addresses = 15728640
max_fuzz_dictionary_values = 6553600
shrink_run_limit = 5000
max_assume_rejects = 65536
gas_report_samples = 256
failure_persist_dir = "cache/invariant"
show_metrics = false

[labels]

[vyper]

[bind_json]
out = "utils/JsonBindings.sol"
include = []
exclude = []

